version: '3.9'

services:
  mongodb:
    image: mongo:7
    container_name: pokemon-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: pokemon_battle
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  app:
    container_name: pokemon-app
    build:
      context: ./app
      dockerfile: Dockerfile
    profiles: ["production"]
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - MONGO_URL=mongodb://mongodb:27017/pokemon_battle
      - PORT=3000
    depends_on:
      - mongodb

  app-dev:
    container_name: pokemon-app-dev
    build:
      context: ./app
      dockerfile: Dockerfile
    profiles: ["development"]
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - MONGO_URL=mongodb://mongodb:27017/pokemon_battle
      - PORT=3000
    depends_on:
      - mongodb
    volumes:
      - ./app/src:/app/src
      - ./app/.env:/app/.env
      - /app/node_modules
      - /app/dist
    command: ["npx", "nodemon"]

volumes:
  mongo_data:
